apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwar-watcher
  labels:
    app: gwar-watcher
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: gwar-watcher
          image: harbor.sof-pilot.net/development/gwar-watcher:latest

