apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwar-watcher
  labels:
    app: gwar-watcher
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      name: gwar-watcher
      labels:
        app: gwar-watcher
    spec:
      containers:
        - name: gwar-watcher
          image: harbor.sof-pilot.net/development/gwar-watcher:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
      restartPolicy: Always
  selector:
    matchLabels:
      app: gwar-watcher
