apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: gwar-watcher
spec:
  virtualhost:
    fqdn: default.example.com
    tls:
      secretName: projectcontour/contour-tls
  routes:
    - services:
        - name: gwar-watcher
          port: 5000


